root: true

parserOptions:
  ecmaVersion: 2018
  sourceType: "module"

env:
  es2017: true
  browser: true

extends: "htmlacademy/vanilla"

rules:
  semi: error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 0
      maxBOF: 0

